[tool.poetry]
name = "telelyzer-transcription-service"
version = "0.1.0"
description = "Telelyzer Transcription Service"
authors = ["Atharva Maskar atharva.maskar@quanthm.com"]
packages = [{ include = "app" }]